# Generated by Django 2.0.6 on 2018-07-01 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stashology_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='stashology__name_b52ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_at'], name='stashology__created_6a6823_idx'),
        ),
        migrations.AddIndex(
            model_name='finish',
            index=models.Index(fields=['name'], name='stashology__name_c7b320_idx'),
        ),
        migrations.AddIndex(
            model_name='finish',
            index=models.Index(fields=['created_at'], name='stashology__created_4a37c3_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['name'], name='stashology__name_936f27_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['created_at'], name='stashology__created_2b6f15_idx'),
        ),
    ]
