# Generated by Django 2.0.6 on 2018-07-01 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stashology_app', '0002_auto_20180701_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=255)),
                ('lighting_type', models.CharField(choices=[('N', 'Natural'), ('A', 'Artificial')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['lighting_type'], name='stashology__lightin_3cacff_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['created_at'], name='stashology__created_7e9923_idx'),
        ),
    ]
