# Generated by Django 2.0.6 on 2018-07-01 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stashology_app', '0003_auto_20180701_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stashology_app.Brand')),
                ('colors', models.ManyToManyField(to='stashology_app.Color')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stashology_app.Finish')),
                ('photos', models.ManyToManyField(to='stashology_app.Photo')),
                ('tags', models.ManyToManyField(to='stashology_app.Tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['name'], name='stashology__name_83d801_idx'),
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['brand'], name='stashology__brand_i_fbf999_idx'),
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['finish'], name='stashology__finish__0d0d76_idx'),
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['colors'], name='stashology__colors_cf5784_idx'),
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['tags'], name='stashology__tags_7604a9_idx'),
        ),
        migrations.AddIndex(
            model_name='polish',
            index=models.Index(fields=['created_at'], name='stashology__created_44799b_idx'),
        ),
    ]
